name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL_TIME_FOR_LANGUAGE: "HTML" # Replace with the desired language
          SHOW_TOTAL_TIME_FOR_LANGUAGE: "CSS" # Replace with the desired language
          SHOW_TOTAL_TIME_FOR_LANGUAGE: "Java" # Replace with the desired language
